[package]
name = "xsk-rs"
version = "0.8.0"
authors = ["Douglas Gray <dbgray01@gmail.com>"]
edition = "2024"
description = "Rust bindings for Linux AF_XDP sockets"
license = "MIT"
repository = "https://github.com/DouglasGray/xsk-rs"
readme = "README.md"
keywords = ["AF_XDP", "XSK", "eBPF", "XDP"]

[dependencies]
bitflags = "2.11.0"
cfg-if = "1.0.4"
libc = "0.2.182"
libxdp-sys = "0.2.4"
log = "0.4.29"

[dev-dependencies]
anyhow = "1.0.101"
crossbeam-channel = "0.5.15"
ctrlc = "3.5.2"
env_logger = "0.11.9"
etherparse = "0.19.0"
futures = "0.3.32"
rand = "0.10.0"
rtnetlink = "0.20.0"
serial_test = "3.3.1"
structopt = "0.3.26"

[dev-dependencies.tokio]
version = "1.49.0"
default-features = false
features =  ["rt-multi-thread", "macros", "sync", "signal", "time"]
